language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
env:
- DOCKER_COMPOSE_VERSION=1.21.1
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- sudo chmod -R 777 src/test/resources/iridium
- ls -la src/test/resources/iridium
- ls -la src/test/resources/iridium/daemon1
- ls -la src/test/resources/iridium/wallet1
- ls -la src/test/resources/iridium/wallet2
- docker-compose up -d
- docker ps -a
- docker-compose logs
after_success:
- bash <(curl -s https://codecov.io/bash)
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- sudo chmod -R 777 src/test/resources/iridium
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - src/test/resources/iridium
deploy:
- provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: sD5fnIVTnTjpjUrxKKQdOG2ltJV2UrAqPbsnOQ6X+YPNZBvEJuC7QZNb5m3N2oHTXDQavGFWVS/83SXmDKcPsKsvcA+3rELDOO6XROAmz+fgOlLPqFFR1Nw0urvX5VQR6kFx2UY1l3caUGZPAiVO37/5Fbv20nxWklSmOEDKgWXsTmv/znoyFh1VBhPNy62oWNVCox20MWr50KzJE3YvXBM0KQU4f5bV7lebh42pQLJfJYAOsq875e+rv0P4G72oE0Tqh/dgyk8n8KUYWmY4DFRKDeTvPST8/wTeiVjIyzzk9qzR8FosbzBKFqDtSKi/KczT13G8/oWv0WLgiKdv4QObPzqZVrxbUTekXZ5B3Qr+0XGaZOF9TpRcUrGwemv2yaZbteZzP60yWbyUdPh638Yt8T9mXhVZat7Xxm6uzyHcLTGceRwPic+ExyGrLJ9VH8OjkYV+VMr2PvcfrVAGmfBAZjx3QHwkl+hrhZaB8w63GZeFBUoFazvds/833jbjRYSSbUpvKFbF4Ec1IRIzJTi345GyshtkQ+8vnQMcHXoPUO+rDARSebSIKeFXPbuiMUn8Hepbb7FqG5Wn6o9uPTJ9MzKnE85Rl7CkCQmFYtc11hduOLRkFqILhJcdmZeDko7XNBQL4n0eg0GnJVU0StT0aZUUCSAWgDOsw+iPkgk=
  file: build/libs/*.jar
  on:
    condition: "$TRAVIS_TAG =~ ^v\d+\.\d+\.\d+(-\S*)?$"
    tags: true
- provider: script
  script: "./gradlew bintray"
  skip_cleanup: true
  on:
    condition: "$TRAVIS_TAG =~ ^v\d+\.\d+\.\d+(-\S*)?$"
    tags: true